### ISSUE TITLE
ダークモード使用中、上部のサーバー選択UIが黒いままなので見ずらい

### ISSUE THREAD

**Issue by kinoko0518** [ibuki2003/pskey#11]
ダークモード使用中、上部のサーバー選択UIが黒いままなので見ずらい
（PSKeyバージョン1.0.0、Android 11にて実行）
![Screenshot_2023-07-26-09-28-06-63_cfca41d764dd6997c1fcf7f57ba4687b](https://github.com/ibuki2003/pskey/assets/99010199/320962ea-bfbc-4be4-ab89-6e1ff1b6e273)

**Comment by ibuki2003** [comment]
使用・報告ありがとうございます!
こちら修正の目処は立っており、次回リリースにて反映予定です。

**Comment by kinoko0518** [comment]
返信ありがとうございます！
MisskeyのUIほぼそのままクライアントアプリ待ってたので助かります！

**Comment by ibuki2003** [comment]
リリースv1.1.0にて修正されました。
